name: Build APK (new way, but KO)

on: workflow_dispatch

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install docker git
        run: |
          sudo apt install docker git
          
      - name: build a docker image
        run: |
           git clone https://github.com/kivy/buildozer.git
           cd buildozer
           docker build --tag=mybuildozer .
           cd ..

      - name: build the apk
        run: |
           cd app
           mkdir .buildozer
           chmod 777 .buildozer
           sudo docker run -v $(pwd)/.buildozer:/home/user/.buildozer -v $(pwd):/home/user/hostcwd mybuildozer android debug
           mv bin/*.apk bin/app.apk
        
      # - name: Build with Buildozer
      #   uses: ArtemSBulgakov/buildozer-action@v1
      #   id: buildozer
      #   with:
      #     workdir: ./app
      #     buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/app.apk
